[general]
poll_interval = 60

[[dns]]
domain = "test.example.com"

[dns.aws]
access_key = "your_access_key"
secret_key = "your_secret_key"
hosted_zone_id = "your_zone_id"
record_name = "your_a_record_name"
record_ttl = 60

# Add more DNS configurations as needed
# [[dns]]
# domain = "another.example.com"
# 
# [dns.aws]
# access_key = "your_access_key"
# secret_key = "your_secret_key"
# hosted_zone_id = "your_zone_id"
# record_name = "your_a_record_name"
# record_ttl = 60
