[general]
domain = "test.example.com"
poll_interval = 60

[aws]
access_key = "your_access_key"
secret_key = "your_secret_key"
hosted_zone_id = "your_zone_id"
record_name = "your_a_record_name"
record_ttl = 60
